name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: env
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@HEAD
    - name: Print staticcheck version
      run: staticcheck -version
    - name: Run go build
      run: make all
    - name: Run go test
      run: make test
    - name: Run go vet
      run: make vet
    - name: Run go fmt
      run: if [ "$(go fmt | wc -l)" -ne 0 ]; then exit 1; fi
